apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - env:
          - name: IPFS_HOST
            valueFrom:
              configMapKeyRef:
                key: IPFS_HOST
                name: ipfs-configmap
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB
                name: postgres-configmap
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_HOST
                name: postgres-configmap
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: postgres-secret
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: postgres-secret
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                key: MONGO_HOST
                name: mongo-configmap
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MONGO_PASSWORD
                name: mongo-secret
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                key: MONGO_USER
                name: mongo-secret
          image: barcode11/api:latest
          name: api-container
          ports:
            - containerPort: 3000
          
---

apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000


