apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
        - image: ipfs/kubo:latest
          name: ipfs-container
          ports:
            - containerPort: 4001
            - containerPort: 4001
              protocol: UDP
            - containerPort: 5001
            - containerPort: 8080
          volumeMounts:
            - name: ipfs-data
              mountPath: /data/ipfs
      volumes:
        - name: ipfs-data
          persistentVolumeClaim:
            claimName: ipfs-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: ipfs-svc
spec:
  selector:
    app: ipfs
  ports:
    - name: p2p-tcp
      port: 4001
      targetPort: 4001
    - name: p2p-udp
      port: 4001
      targetPort: 4001
      protocol: UDP
    - name: rpc-api
      port: 5001
      targetPort: 5001
    - name: gateway
      port: 8080
      targetPort: 8080
