apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
        - image: ipfs/kubo:latest
          name: ipfs-container
          ports:
            - containerPort: 4001
            - containerPort: 4001
              protocol: UDP
            - containerPort: 5001
            - containerPort: 8080
          volumeMounts:
            - name: ipfs-data
              mountPath: /data/ipfs
      volumes:
        - name: ipfs-data
          persistentVolumeClaim:
            claimName: ipfs-pvc