apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-api
  template:
    metadata:
      labels:
        app: nestjs-api
    spec:
      containers:
        - name: nestjs-api
          image: barcode11/apinestjs:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: env
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-api-service
spec:
  selector:
    app: nestjs-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
